### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by KCErb** [mixflame/SwissDB#11]
So what's next?

Here's my wishlist:
1. Automatic id column
2. Relations like `belongs_to`, `has_many` not sure how complex we want to go there.
3. migrations

**Comment by mixflame** [comment]
1. We sort of have already. We can default to "id" already as the default
   id column. Unless you're thinking of something else. Can you expand on what
   your idea is here?
2. This is actually a great idea. We should definitely try to do this one.
   I'm pretty sure CDQ has this and AR definitely does.
3. This will be hard without a refactor of the current design. To migrate
   the database, we have to support changing the Android SQLite DB version
   number. This will cause a drop/create of all tables ... hopefully. But
   right now there's not even support for it. Still a good idea. We may be
   able to do it by using non-android-API means but that doesn't seem as
   attractive of an idea to me.

Thanks @KCErb :D :+1:

**Comment by mixflame** [comment]
Forgot to say why #3 is currently hard by design. Db VERSION is a global
right now, migrations are based on that.

**Comment by KCErb** [comment]
Thanks for the response! Here's my follow-up:
1. Don't we have to create an id column if we want an id? In my app I needed to make a user id by hand like this:
   
   ``` ruby
   next_id = User.all.to_a == [] ? 0 : User.last.id + 1
   User.create( id: next_id, name: input_text, created_at: Time.now )
   ```
   
   But I'd rather skip all that about the id. Maybe I'm missing the right way to do this :)
2.  Cool, I'll see what I can do about this. Along these lines let's throw in automatic time stamping like AR?
3. Yes, I see in the README that the way things are makes migrating hard. But I'm wondering if it's on the roadmap. I'd like it to be. Along with some other tools that help me manage the device's database. For example right now I have a little rake task for pulling the database from the phone so that I can open it and look inside. It'd be nice to have tasks that push back my changes as well (for example).

**Comment by mixflame** [comment]
1. You're probably correct. In our app we use an external id and translate
   it to a different column which _is_ created. If this makes sense to you I'd
   go ahead and add it.
2. Automatic time stamping would be great! This and the associations will
   definitely bring the project to a much higher production quality.
3. Yes, it's probably all possible, and we definitely want to look at
   having this ability for sure.  :+1: :us: :D

Let me know if you need anything.

Thanks.

**Comment by mixflame** [comment]
I'm guessing once we get tests and this stuff in we can turn around and call it our 1.0.0 release. It makes sense to me that these are a good "0.3.0 worth" or more of improvements and we're at 0.7.0. :+1:

**Comment by KCErb** [comment]
Oh yeah, that would all be very spiffy. Looking forward to it! :sunglasses: 

BTW I use ZenHub for some of my other projects. I'd be very interested in getting access to this Repo, opening issues for these roadmap items and setting up a 1.0.0 milestone.

Then with ZenHub we can assign storyboard points to issues and track progress in a Burndown chart.

I mainly got interested in ZenHub when I wanted to move my programming "To Dos" from a bunch of little text files to one central thing. But I'm cool with it if you'd rather I didn't  :)

**Comment by mixflame** [comment]
I've never used ZenHub but I'd be willing to use it. I'm willing to add you as a collaborator on the repository. I will add you to the collaborators and you can control this repository. Please be careful, but I trust you to be safe. I'll add you now. Go ahead and open a ZenHub for this project. My email is jsilverman2 AT geemail DOT com

(where "geemail" is "gmail", i wanted to mess up the email crawlers)

**Comment by mixflame** [comment]
You now have full access to this repo. Let me know if you need anything else. Thanks.

**Comment by KCErb** [comment]
Thanks @jsilverMDX! I'll always develop on a branch and use the PR system to get more eyes on it before a merge, rest assured.

**Comment by KCErb** [comment]
Cool, so I think we can close this now that there are issues for each of these items and a milestone. Agreed?

**Comment by mixflame** [comment]
Yeah.
