### ISSUE TITLE
Create should return instance of model

### ISSUE THREAD

**Issue by KCErb** [mixflame/SwissDB#19]
Right now if I want to make a car:

``` ruby
car = Car.create(is_red: true, mileage: 70000)
```

won't work because create returns a java Long as per [this doc](http://developer.android.com/reference/android/database/sqlite/SQLiteDatabase.html#insert%28java.lang.String, java.lang.String, android.content.ContentValues%29) on insert.

I think the desired behavior is to get back an instance of the car class yeah?

**Comment by mixflame** [comment]
Correct. Easy way to do this is calling the new model constructor and
returning that object (or something like that.)

**Comment by mixflame** [comment]
This is fixed.
