### ISSUE TITLE
Cursors are never closed

### ISSUE THREAD

**Issue by mixflame** [mixflame/SwissDB#24]
This will cause an app crash after a while.

```
E/CursorWindow(14954): Could not allocate CursorWindow '/data/data/APPNAME/databases/swissdb' of size 2097152 due to error -12.
W/dalvikvm(14954): JNI WARNING: JNI method called with exception pending
W/dalvikvm(14954):              in LAPPNAME/PMBaseAdapter;.getView:(ILandroid/view/View;Landroid/view/ViewGroup;)Landroid/view/View; (GetMethodID)
W/dalvikvm(14954): Pending exception is:
I/dalvikvm(14954): android.database.CursorWindowAllocationException: Cursor window allocation of 2048 kb failed. # Open Cursors=882 (# cursors opened by this proc=882)
```

After deallocate or something, close them with 

``` ruby
cursor.close
```

**Comment by mixflame** [comment]
Update:

I've tried working on this. Closing the cursor in #finalize won't work.

It's just that finalize never gets called during the life of the program.

We need some other way to detect that the cursor isn't used by the model anymore, any cleanup with cursor.close.

It's sort of boggling my mind right now because how else should we know that the last reference to the object was used besides #finalize?

**Comment by mixflame** [comment]
Update:

Based on this: https://github.com/zoocasa/activerecord-postgresql-cursors/blob/5292b143441d7ffb432eb539e23569dd4793e84e/lib/activerecord-postgresql-cursors.rb

It looks like we need to "ensure" the cursor is closed after an operation such as #first, #last, #to_a or any operator where a cursor was used and a model was returned. Then from there we need to fully rely on the model for data.

**Comment by KCErb** [comment]
That sounds like a solid approach. I did something like that to close my IO streams in the SQL reader: https://github.com/jsilverMDX/SwissDB/pull/25/files#diff-d1392fc2bdf284b58a0f831d9ec2d424R38

**Comment by mixflame** [comment]
Think I fixed it. Closing.
