### ISSUE TITLE
Yay Swiss DB

### ISSUE THREAD

**Issue by KCErb** [mixflame/SwissDB#5]
Hi there,

Just started playing with Swiss DB today and having some fun. I might have a pull request or two to submit in a bit but I first want to make sure that I get basic things working first.

One problem I'm running into is that I'm not sure how to browse my database! Do you recommend a tool (sqlite browser)? Also I can't find my database. I see people sayings its in `/data/data/...` but I don't have a `/data` folder that I can find so I'm not sure where to start.

Thanks for the great tool, I really like what I see and hope I can contribute some code.

-KC

**Comment by mixflame** [comment]
Hey @KCErb 

To browse the database, connect adb and run sqlite through the terminal as described here:

http://developer.android.com/tools/help/sqlite3.html

or pull the file and open it in a Sqlite browser (there are a few.): 

http://stackoverflow.com/questions/19194576/how-to-view-the-sqlite-database-in-device-android

The database file itself will be located in /data/data... on the actual device file system in adb (which will connect you via SSH)

Let me know if there is anything else you need.

Thanks for trying Swiss! I'm glad you like it! Always open to contributions, full credit will be given.

(Edit: Lemme know if you need an invite to the RubyMotion Android Slack room as well. I can ask someone to get you one.)

-J

**Comment by KCErb** [comment]
Hi @jsilverMDX I got the basics of my app working and have a few thoughts comments and questions on SwissDB. I'm going to submit some of these as pull requests and won't be offended if you reject them. I'll open others as separate issues.

Thanks for your help and yes, I'd like an invite to RubyMotion Android Slack. I didn't know it existed!

**Comment by mixflame** [comment]
Hey @KCErb that's great! Glad you were able to get it operational. I'll be
waiting to check out the PRs! Likely they will be modified and accepted
instead of outright rejected.  :)

**Comment by mixflame** [comment]
Hey @KCErb I got the link for you. You can sign up at
motioneers.herokuapp.com. There's an Android, iOS, TVOS and general room.
Thanks

**Comment by KCErb** [comment]
BTW the heroku app is broken :(

**Comment by mixflame** [comment]
I'm asking around. I swear that link used to work lol
