### ISSUE TITLE
Fix Inflections#Pluralize and change all references to current_schema to use tableized table_name

### ISSUE THREAD

**Issue by KCErb** [mixflame/SwissDB#6]
In your README and the cdq schema it looks like the `entity` method wants the class name, not a table name, but the source looks otherwise:

https://github.com/jsilverMDX/SwissDB/blob/master/lib/swiss_db/db.rb#L33-L40

Which should we use? Rails uses snake_case like I see here, CDQ uses CamelCase.

**Comment by mixflame** [comment]
You're correct here there is an error. The class name SHOULD be passed, but
the class name should be "tableized" before the table is created. I looked
at my code ...and then gem works. But I'm not sure if this is an issue
right now. Can you test if the created database is able to be
inserted/selected against? If you look at
https://github.com/jsilverMDX/SwissDB/blob/master/lib/swiss_db/swiss_model.rb#L24-L27
when the class name is passed to the Model, it is tableized. So it expects
something like "BigCar" to be turned into "big_cars". Let me know if you
think this is a real issue. From the looks of it alone it is.

**Comment by KCErb** [comment]
So the code you're pointing to correctly gets a table name from a model's class name. The trouble comes in where the `current_schema` hash gets it's key for the table from the argument passed to `entity` in your schema. 

What I'm finding is this.

Let's say this is your schema:

``` ruby
schema "0001" do
  entity "ServiceHour" do
    integer :id
    # etc...
  end
end
```

then the `current_schema` hash looks like this

``` ruby
{"ServiceHour"=>{"id"=>"INTEGER"}}
```

then when you go to do a lookup we get a call like this

``` ruby
current_schema[model.table_name]
```

which is `nil` because `model.table_name` is `service_hour` and the hash doesn't have that key.

Does the above sound right to you?

**Comment by mixflame** [comment]
Yes you're correct. I'm going to rename the issue if I can.

It should really look like this.

``` ruby
{"service_hours"=>{"id"=>"INTEGER"}}
```

**Comment by mixflame** [comment]
Ok. That should should clear up the goals here.

Use "table_names" everywhere after it has been parsed from Class Name (schema reader, model, cursor model, etc).

When that's done I'll merge with full credit in the README.

Thanks :) :+1: :us:

**Comment by KCErb** [comment]
Thanks it does clear things up!

**Comment by mixflame** [comment]
Fixed. Awesome stuff. Thanks @KCErb !!!! :D
